name: Install Dependencies

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull requests to the 'main' branch

jobs:
  install:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the code in the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js environment
      with:
        node-version: '14'  # Specify the Node.js version for your project

    - name: Install dependencies
      run: |
        npm install  # Run npm install to install dependencies
        # OR if you're using yarn, replace with:
        # yarn install
